site:
  title: Issues Browser
  url: https://docs.devcentr.org/issues-browser
  start_page: issues-browser::index.adoc
content:
  sources:
    - url: .
      branches: [HEAD]
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui
output:
  dir: ./public
